name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: amitkulkarni1712/todo-flask:latest
    - name: Checkout Helm Charts
      uses: actions/checkout@v3.0.0
      with:
        repository: amitkulkarni1712/todo-helm-chart
        
    
