name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub 
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag amitkulkarni1712/todo-flask:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push amitkulkarni1712/todo-flask:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag amitkulkarni1712/todo-flask:latest
    - name: Push the latest Docker image to hub
      run: docker push amitkulkarni1712/todo-flask:latest
